### PR TITLE
basic tests

### PR DESCRIPTION
**Pull request by ianhi**

### CODE REVIEW

**Comment by ianhi** [comment]
@henrypinkard seems like `start_headless` isn't working on CI. Any ideas why?

**Comment by ianhi** [comment]
mac tests are failing because the java location detection in pycro doesn't work with how it gets set up there.

windows because the timeout isn't actually configurable: https://github.com/micro-manager/pycro-manager/issues/386#issuecomment-1071274231

**Comment by ianhi** [comment]
actually they are failing because the latest released pycromanager version is broken

**Comment by ianhi** [comment]
window 3.8 and 3.9 hung after completing pytest for some reason

**Comment by henrypinkard** [comment]
> mac tests are failing because the java location detection in pycro doesn't work with how it gets set up there.

Yeah I think probably the best solution is java being added to mac installer.
https://github.com/micro-manager/micro-manager/issues/1402

But I'm not sure how to make this robust in the mean time. Maybe just worth disabling for now on Mac

> windows because the timeout isn't actually configurable: https://github.com/micro-manager/pycro-manager/issues/386#issuecomment-1071274231

Fixed https://github.com/micro-manager/pycro-manager/pull/389


> actually they are failing because the latest released pycromanager version is broken

Any idea why?

**Comment by ianhi** [comment]
I think this check is not correct:
```
        if not os.path.isfile(java_loc):
>           raise Exception(java_loc + ' does not exist')
```

because that checks relative to the python working directory, not whereever java is actually installed.


> >    actually they are failing because the latest released pycromanager version is broken
> Any idea why?

You hadn't released https://github.com/micro-manager/pycro-manager/pull/384 yet

**Comment by ianhi** [comment]
also I suspec the hanging is due to some lingering subprocesses or not closing the bridge (https://github.com/micro-manager/pycro-manager/issues/390)

**Comment by ianhi** [comment]
ahhhh oh no

pymmc+ does nto convert to snake case, but pycromanager does. so we have issues like this:
```
    def test_for_smoke():
        mm_app_path = Path(find_micromanager())
        start_headless(
            str(mm_app_path), str(mm_app_path / "MMConfig_demo.cfg"), timeout=5000
        )
        core = pycroCorePlus()
>       core.snapImage()
E       AttributeError: 'mmcorej_CMMCore' object has no attribute 'snapImage'
```

that will need to worked out.

**Comment by henrypinkard** [comment]
> also I suspec the hanging is due to some lingering subprocesses or not closing the bridge ([micro-manager/pycro-manager#390](https://github.com/micro-manager/pycro-manager/issues/390))

Yeah that makes sense. Is it possible to just call `quit()` after the test in python, so that the process closes, which should auto clean up the java headless process?

> pymmc+ does nto convert to snake case, but pycromanager does. so we have issues like this:

you can do `Bridge(convert_camel_case=False)` or `Core(convert_camel_case=False)`

> I think this check is not correct:
> 
> ```
>         if not os.path.isfile(java_loc):
> >           raise Exception(java_loc + ' does not exist')
> ```
> 
> because that checks relative to the python working directory, not whereever java is actually installed.

Do you know what the correct call is?

**Comment by ianhi** [comment]
> Do you know what the correct call is?

I would just remove that check. Calling `java` in the subprocess should find the right thing. You can check the return value of the subprocess to check if it failed. 

> Yeah that makes sense. Is it possible to just call quit() after the test in python, so that the process closes, which should auto clean up the java headless process?

I don't think so. Because `quit` only makes sense in the context of an interactive repl. Better would be to have a mechnism in pycromanager to kill the subprocess and then do something like this pytest fixture: https://til.simonwillison.net/pytest/subprocess-server

> you can do Bridge(convert_camel_case=False) or Core(convert_camel_case=False)

That's great, but I'm suspicious that it will fail becuase `start_headless` doesn't pass core args all the way through and then this code: 
https://github.com/micro-manager/pycro-manager/blob/f8d62a935d8cb156306f994fdd7df556be6f62f5/pycromanager/bridge.py#L227-L235 will (I think) grab the core/bridge instance that start_headless created

**Comment by ianhi** [comment]
merging for local development

**Comment by henrypinkard** [comment]
I messed around with it some more, and have come to the conclusions that it is...confusing.

If you switch around the module resolution order, `__init__` gets called as expected.

But the pycromanager `Core` object is quite weird, because its not statically declared, and is created by a factory method:

https://github.com/micro-manager/pycro-manager/blob/d9f34fe10a761863ae2443c43c251d8d2c23b95a/pycromanager/java_classes.py#L59

So there's additional weird stuff like the pycromanager `Core` object not having having the `__init__` you might expect, and instead you would need to call:

```python
# pycroCore().__init__(convert_camel_case=False)
bridge = zmqBridge(convert_camel_case=False)
bridge._construct_java_object("mmcorej.CMMCore")
```

Unless you have other ideas, I'm pretty stumped with this, and I think it would be easier to pursue creating something more explicit. I also still haven't quite wrapped by head around why we're making pycroCore and mmcorepyplus at the same level. Shouldn't mmcorepyplus sit above either pycrocore or mmcorepy, so that it can dispatch its wrapper methods to each one?

lmk what you think we should try next.

**Pull request merged**
